# Created by StreamBase LiveView 2.1.6.3072
--- 
GlobalProcessorName: App
Configuration: !java.util.LinkedHashMap
  ModuleName: Test.sbapp
  ModuleFolder: "C:/workspace/PSA_7.7/PSA"
  Builder: com.streambase.liveview.engine.ModuleGroup.ModuleGroupBuilder
  Template: ModuleGroup.template
  PublicStreams: 
    - !java.util.LinkedHashMap
      Stream: OutputStream8
      Type: output
      Schema: !java.util.LinkedHashMap
        Name: ~
        Fields: 
          - !java.util.LinkedHashMap
            field: jmsHeader tuple
          - !java.util.LinkedHashMap
            field: jmsProperties tuple
          - !java.util.LinkedHashMap
            field: messageAckID string
          - !java.util.LinkedHashMap
            field: sessionID string
          - !java.util.LinkedHashMap
            field: AGV_ID string
          - !java.util.LinkedHashMap
            field: GoingTo string
          - !java.util.LinkedHashMap
            field: lat_lon list
    - !java.util.LinkedHashMap
      Stream: LDM_Latency
      Type: output
      Schema: !java.util.LinkedHashMap
        Name: ~
        Fields: 
          - !java.util.LinkedHashMap
            field: latency_JMS long
          - !java.util.LinkedHashMap
            field: latency_ECS_JMS long
          - !java.util.LinkedHashMap
            field: record_time timestamp
      IOMappings: 
        - !java.util.LinkedHashMap
          Mapping: Latency.DataIn
    - !java.util.LinkedHashMap
      Stream: OutputStream7
      Type: output
      Schema: !java.util.LinkedHashMap
        Name: ~
        Fields: 
          - !java.util.LinkedHashMap
            field: time timestamp
          - !java.util.LinkedHashMap
            field: AGV_ID string
          - !java.util.LinkedHashMap
            field: Status string
          - !java.util.LinkedHashMap
            field: GoingTo string
          - !java.util.LinkedHashMap
            field: lat_lon list
          - !java.util.LinkedHashMap
            field: ContainerNumber string
    - !java.util.LinkedHashMap
      Stream: OutputStream6
      Type: output
      Schema: !java.util.LinkedHashMap
        Name: ~
        Fields: 
          - !java.util.LinkedHashMap
            field: jmsHeader tuple
          - !java.util.LinkedHashMap
            field: jmsProperties tuple
          - !java.util.LinkedHashMap
            field: messageAckID string
          - !java.util.LinkedHashMap
            field: sessionID string
          - !java.util.LinkedHashMap
            field: AGV_ID string
          - !java.util.LinkedHashMap
            field: GoingTo string
          - !java.util.LinkedHashMap
            field: lat_lon list
    - !java.util.LinkedHashMap
      Stream: OutputStream5
      Type: output
      Schema: !java.util.LinkedHashMap
        Name: ~
        Fields: 
          - !java.util.LinkedHashMap
            field: veh string
          - !java.util.LinkedHashMap
            field: Lat double
          - !java.util.LinkedHashMap
            field: Long double
          - !java.util.LinkedHashMap
            field: ContainerNumber string
          - !java.util.LinkedHashMap
            field: Status string
    - !java.util.LinkedHashMap
      Stream: LDM_AGVUpdate
      Type: output
      Schema: !java.util.LinkedHashMap
        Name: ~
        Fields: 
          - !java.util.LinkedHashMap
            field: veh string
          - !java.util.LinkedHashMap
            field: Lat double
          - !java.util.LinkedHashMap
            field: Long double
          - !java.util.LinkedHashMap
            field: ContainerNumber string
          - !java.util.LinkedHashMap
            field: Status string
      IOMappings: 
        - !java.util.LinkedHashMap
          Mapping: dtable.DataIn
